import { FluentProvider, webLightTheme, Button, Tab, TabList, Text } from '@fluentui/react-components';
import { useEffect, useState } from 'react';
import { api } from './services/api';
import { getCurrentEmailPayload } from './services/outlook';
import { Dashboard } from './components/Dashboard';
import { TaskList } from './components/TaskList';
import { DraftAssistant } from './components/DraftAssistant';
import type { Dashboard as DashboardType, Task } from './types';
import './styles.css';
export default function App(){const [dash,setDash]=useState<DashboardType|null>(null);const [tasks,setTasks]=useState<Task[]>([]);const [tab,setTab]=useState('dashboard');async function load(){setDash(await api.dashboard());setTasks(await api.tasks())}useEffect(()=>{load();const i=setInterval(load,30000);return()=>clearInterval(i)},[]);async function ingest(){const p=await getCurrentEmailPayload(); if(p){await api.ingestCurrent(p); await load();}}async function complete(id:number){await api.complete(id);await load()}return <FluentProvider theme={webLightTheme}><main><header><Text size={600} weight="bold">AI Mailbox Manager</Text><Button appearance="primary" onClick={ingest}>Analyze Current Email</Button></header><TabList selectedValue={tab} onTabSelect={(_,d)=>setTab(String(d.value))}><Tab value="dashboard">Dashboard</Tab><Tab value="tasks">Prioritized Tasks</Tab><Tab value="pending">Pending Items</Tab><Tab value="draft">Draft Assistant</Tab><Tab value="settings">Settings</Tab></TabList>{tab==='dashboard'&&dash&&<><Dashboard data={dash}/><TaskList title={`Today's Focus (${dash.workload_minutes} min)`} tasks={dash.today_focus} onComplete={complete}/></>}{tab==='tasks'&&<TaskList title="Prioritized Tasks" tasks={tasks} onComplete={complete}/>} {tab==='pending'&&<TaskList title="Aging Emails & Overdue Tasks" tasks={tasks.filter(t=>t.status!=='completed')} onComplete={complete}/>} {tab==='draft'&&<DraftAssistant/>}{tab==='settings'&&<section className="settings"><h2>Settings</h2><p>LLM provider: Ollama local. Supported models: Llama 3, Qwen, Mistral. OpenAI fallback remains disabled unless explicitly enabled in local settings.</p><p>Priority rules use due date proximity, sender importance, escalation language, pending duration, sentiment, and business impact.</p></section>}</main></FluentProvider>}
